-- Generated by Oracle SQL Developer Data Modeler 17.4.0.355.2131
--   at:        2018-08-18 17:35:39 CST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE dim_ciudaddestino (
    idciudaddestino   INTEGER NOT NULL,
    ciudad_destino    VARCHAR2(100)
);

ALTER TABLE dim_ciudaddestino ADD CONSTRAINT dim_ciudaddestino_pk PRIMARY KEY ( idciudaddestino );

CREATE TABLE dim_ciudadorigen (
    idciudadorigen   INTEGER NOT NULL,
    ciudad_origen    VARCHAR2(100)
);

ALTER TABLE dim_ciudadorigen ADD CONSTRAINT dim_ciudadorigen_pk PRIMARY KEY ( idciudadorigen );

CREATE TABLE dim_pasajeros (
    idpasajero        INTEGER NOT NULL,
    nombre_pasajero   VARCHAR2(150)
);

ALTER TABLE dim_pasajeros ADD CONSTRAINT dim_pasajeros_pk PRIMARY KEY ( idpasajero );

CREATE TABLE dim_tiempo (
    idtiempo    INTEGER NOT NULL,
    dia         VARCHAR2(20),
    semana      INTEGER,
    mes         VARCHAR2(50),
    trimestre   INTEGER,
    anio        INTEGER
);

ALTER TABLE dim_tiempo ADD CONSTRAINT dim_tiempo_pk PRIMARY KEY ( idtiempo );

CREATE TABLE dim_vuelos (
    idvuelo          INTEGER NOT NULL,
    registro_avion   VARCHAR2(100),
    nombre_piloto    VARCHAR2(150)
);

ALTER TABLE dim_vuelos ADD CONSTRAINT dim_vuelos_pk PRIMARY KEY ( idvuelo );

CREATE TABLE hechos_vuelos (
    idvuelo           INTEGER NOT NULL,
    idpasajero        INTEGER NOT NULL,
    tiempo_idtiempo   INTEGER NOT NULL,
    idciudadorigen    INTEGER NOT NULL,
    idciudaddestino   INTEGER NOT NULL,
    ventas            NUMBER
);

ALTER TABLE hechos_vuelos
    ADD CONSTRAINT dim_ciudaddestino_fk FOREIGN KEY ( idciudaddestino )
        REFERENCES dim_ciudaddestino ( idciudaddestino );

ALTER TABLE hechos_vuelos
    ADD CONSTRAINT dim_ciudadorigen_fk FOREIGN KEY ( idciudadorigen )
        REFERENCES dim_ciudadorigen ( idciudadorigen );

ALTER TABLE hechos_vuelos
    ADD CONSTRAINT dim_pasajeros_fk FOREIGN KEY ( idpasajero )
        REFERENCES dim_pasajeros ( idpasajero );

ALTER TABLE hechos_vuelos
    ADD CONSTRAINT dim_tiempo_fk FOREIGN KEY ( tiempo_idtiempo )
        REFERENCES dim_tiempo ( idtiempo );

ALTER TABLE hechos_vuelos
    ADD CONSTRAINT dim_vuelos_fk FOREIGN KEY ( idvuelo )
        REFERENCES dim_vuelos ( idvuelo );


